<a href="https://colab.research.google.com/github/sofiaKon/books-web-scraping-analysis/blob/main/bookstoscape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Books to scape

*Introduction*

Web scraping is a technique used to extract structured data from websites by analyzing their HTML structure. In this task, the BeautifulSoup library was used to parse web pages and retrieve relevant information from the website Books to Scrape. The project focuses on collecting book data from multiple categories and organizing it into a structured dataset for further analysis.

*Objective*

The objective of this task is to:

Extract book data from 10 predefined categories
Collect information for 10 books in each category
Retrieve key attributes such as:

*   Book title
*   Category   
*   Price

Convert the collected data into a structured format (DataFrame)
Transform price values into numeric format for analysis
Identify and present the top 10 most expensive books

In [46]:
import requests
from bs4 import BeautifulSoup

url = "http://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

In [47]:
# 1.found all h3 tags
titles = [a['title'] for a in soup.select('h3 a')]

# result
for title in titles:
    print(title)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [48]:
import pandas as pd

df_titles = pd.DataFrame(titles, columns=['Book Titles'])
df_titles

                                          Book Titles
0                                A Light in the Attic
1                                  Tipping the Velvet
2                                          Soumission
3                                       Sharp Objects
4               Sapiens: A Brief History of Humankind
5                                     The Requiem Red
6   The Dirty Little Secrets of Getting Your Dream...
7   The Coming Woman: A Novel Based on the Life of...
8   The Boys in the Boat: Nine Americans and Their...
9                                     The Black Maria
10     Starving Hearts (Triangular Trade Trilogy, #1)
11                              Shakespeare's Sonnets
12                                        Set Me Free
13  Scott Pilgrim's Precious Little Life (Scott Pi...
14                          Rip it Up and Start Again
15  Our Band Could Be Your Life: Scenes from the A...
16                                               Olio
17  Mesaerion: The Best Science Fiction Stories 18...
18                       Libertarianism for Beginners
19                            It's Only the Himalayas

In [49]:
for book in soup.find_all("h3"):
    print(book)
    print(book.a.text)
    print('\n')

<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
A Light in the ...


<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
Tipping the Velvet


<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
Soumission


<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
Sharp Objects


<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
Sapiens: A Brief History ...


<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
The Requiem Red


<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
The Dirty Little Secrets ...


<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
The Coming Woman: A ...


<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
The Boys in the ...


<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
The Black Maria


<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
Starving Hearts (Triangular Trade ...


<h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
Shakespeare's Sonnets


<h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
Set Me Free


<h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
Scott Pilgrim's Precious Little ...


<h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
Rip it Up and ...


<h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
Our Band Could Be ...


<h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
Olio


<h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
Mesaerion: The Best Science ...


<h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
Libertarianism for Beginners


<h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
It's Only the Himalayas

In [50]:
import requests
from bs4 import BeautifulSoup
import time

# file name
file_name = "book_titles.txt"

# 1. open like 'w'
with open(file_name, "w", encoding="utf-8") as f:

    # 2. repeat 1~10
    for page in range(1, 11):

        url = f"https://books.toscrape.com/catalogue/page-{page}.html"

        try:
            response = requests.get(url)

            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')
                books = soup.select('h3 a')

                f.write(f"--- Page {page} ---\n")

                for book in books:
                    title = book.get('title')
                    if title:
                        f.write(title + "\n")

                print(f"Success: Page {page} saved")
            else:
                print(f"Error: Page {page}.")

        except Exception as e:
            print(f"Error: {e}")

        time.sleep(0.5)

print(f"\ '{file_name}' Check the file!")

<>:40: SyntaxWarning: invalid escape sequence '\ '
<>:40: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipykernel_11831/3195578340.py:40: SyntaxWarning: invalid escape sequence '\ '
  print(f"\ '{file_name}' Check the file!")

Success: Page 1 saved
Success: Page 2 saved
Success: Page 3 saved
Success: Page 4 saved
Success: Page 5 saved
Success: Page 6 saved
Success: Page 7 saved
Success: Page 8 saved
Success: Page 9 saved
Success: Page 10 saved
\ 'book_titles.txt' Check the file!

In [61]:
import requests
from bs4 import BeautifulSoup
import time

base_url = "http://books.toscrape.com/"
response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

category_tags = soup.select('ul.nav-list ul li a')[0:10]

dataset = []

for cat in category_tags:
    cat_name = cat.get_text(strip=True)
    cat_url = base_url + cat.get('href')

    print(f"Collecting category: {cat_name}...")

    cat_response = requests.get(cat_url)
    cat_soup = BeautifulSoup(cat_response.text, "html.parser")

    book_items = cat_soup.select('article.product_pod')[:10]

    for item in book_items:

        title = item.select_one('h3 a').get('title')

        price = item.select_one('p.price_color').get_text(strip=True)

        dataset.append([cat_name, title, price])
    time.sleep(0.2)

print("\n--- Collection complete (total {} items) ---".format(len(dataset)))
for data in dataset[:5]:
    print(data)

# 4. Save file using Binary I/O (optional)
with open("books_dataset.bin", "wb") as f:
    for entry in dataset:
        line = f"{entry[0]} | {entry[1]} | {entry[2]}\n"
        f.write(line.encode('utf-8'))

Collecting category: Travel...
Collecting category: Mystery...
Collecting category: Historical Fiction...
Collecting category: Sequential Art...
Collecting category: Classics...
Collecting category: Philosophy...
Collecting category: Romance...
Collecting category: Womens Fiction...
Collecting category: Fiction...
Collecting category: Childrens...

--- Collection complete (total 100 items) ---
['Travel', "It's Only the Himalayas", 'Â£45.17']
['Travel', 'Full Moon over Noahâ\x80\x99s Ark: An Odyssey to Mount Ararat and Beyond', 'Â£49.43']
['Travel', 'See America: A Celebration of Our National Parks & Treasured Sites', 'Â£48.87']
['Travel', 'Vagabonding: An Uncommon Guide to the Art of Long-Term World Travel', 'Â£36.94']
['Travel', 'Under the Tuscan Sun', 'Â£37.33']

In [52]:
import pandas as pd

file_path = 'books_dataset.bin'
data = []

with open(file_path, 'rb') as f:
    for line_bytes in f:
        line = line_bytes.decode('utf-8').strip()
        parts = line.split(' | ')
        if len(parts) == 3:
            data.append(parts)

df_books_dataset = pd.DataFrame(data, columns=['Category', 'Title', 'Price'])
df_books_dataset

     Category                                              Title    Price
0      Travel                            It's Only the Himalayas  Â£45.17
1      Travel  Full Moon over Noahâs Ark: An Odyssey to Mou...  Â£49.43
2      Travel  See America: A Celebration of Our National Par...  Â£48.87
3      Travel  Vagabonding: An Uncommon Guide to the Art of L...  Â£36.94
4      Travel                               Under the Tuscan Sun  Â£37.33
..        ...                                                ...      ...
95  Childrens                  Walt Disney's Alice in Wonderland  Â£12.96
96  Childrens                                       Twenty Yawns  Â£22.08
97  Childrens                                          Rain Fish  Â£23.57
98  Childrens                                    Once Was a Time  Â£18.28
99  Childrens                              Luis Paints the World  Â£53.95

[100 rows x 3 columns]

In [53]:
df_books_dataset['Title'] = df_books_dataset['Title'].str.replace('â', "'")
print(df_books_dataset.head())

  Category                                              Title    Price
0   Travel                            It's Only the Himalayas  Â£45.17
1   Travel  Full Moon over Noah's Ark: An Odyssey to Mount...  Â£49.43
2   Travel  See America: A Celebration of Our National Par...  Â£48.87
3   Travel  Vagabonding: An Uncommon Guide to the Art of L...  Â£36.94
4   Travel                               Under the Tuscan Sun  Â£37.33

In [54]:
df_books_dataset

     Category                                              Title    Price
0      Travel                            It's Only the Himalayas  Â£45.17
1      Travel  Full Moon over Noah's Ark: An Odyssey to Mount...  Â£49.43
2      Travel  See America: A Celebration of Our National Par...  Â£48.87
3      Travel  Vagabonding: An Uncommon Guide to the Art of L...  Â£36.94
4      Travel                               Under the Tuscan Sun  Â£37.33
..        ...                                                ...      ...
95  Childrens                  Walt Disney's Alice in Wonderland  Â£12.96
96  Childrens                                       Twenty Yawns  Â£22.08
97  Childrens                                          Rain Fish  Â£23.57
98  Childrens                                    Once Was a Time  Â£18.28
99  Childrens                              Luis Paints the World  Â£53.95

[100 rows x 3 columns]

In [55]:
# Remove the currency symbol 'Â£' and convert 'Price' to numeric
df_books_dataset['Price_Numeric'] = df_books_dataset['Price'].str.replace('Â£', '').astype(float)

# Sort by 'Price_Numeric' in descending order and get the top 10
top_10_highest_price_books = df_books_dataset.sort_values(by='Price_Numeric', ascending=False).head(10)

print("Top 10 books with the highest prices:")
print(top_10_highest_price_books[['Title', 'Price_Numeric']])

Top 10 books with the highest prices:
                                                Title  Price_Numeric
46                                            Candide          58.63
51       The Death of Humanity: and the Case for Life          58.11
93  The White Cat and the Monk: A Retelling of the...          58.08
70  I Had a Nice Time And Other Lies...: How to fi...          57.36
47                                        Animal Farm          57.22
7                    A Year in Provence (Provence #1)          56.88
12                                The Past Never Ends          56.50
92                    The Secret of Dreadwillow Carse          56.13
66                   Suddenly in Love (Lake Haven #1)          55.99
22            A Flight of Arrows (The Pathfinders #2)          55.53

In [56]:
df_books_dataset.sort_values(by='Price_Numeric', ascending=False)

,Category,Title,Price,Price_Numeric
46,Classics,Candide,Â£58.63,58.63
51,Philosophy,The Death of Humanity: and the Case for Life,Â£58.11,58.11
93,Childrens,The White Cat and the Monk: A Retelling of the...,Â£58.08,58.08
70,Womens Fiction,I Had a Nice Time And Other Lies...: How to fi...,Â£57.36,57.36
47,Classics,Animal Farm,Â£57.22,57.22
...,...,...,...,...
36,Sequential Art,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",Â£13.61,13.61
94,Childrens,Little Red,Â£13.47,13.47
95,Childrens,Walt Disney's Alice in Wonderland,Â£12.96,12.96
17,Mystery,Tastes Like Fear (DI Marnie Rome #3),Â£10.69,10.69
38,Sequential Art,Patience,Â£10.16,10.16

In [57]:
df_books_dataset.describe()

       Price_Numeric
count     100.000000
mean       34.593500
std        15.323483
min        10.160000
25%        19.922500
50%        34.250000
75%        49.010000
max        58.630000

#Conclusion

In this task, web scraping techniques were successfully applied to extract structured data from a real website. Using BeautifulSoup, book titles and prices were collected across multiple categories and organized into a DataFrame. After preprocessing the price data into numeric format, the dataset was analyzed to identify the top 10 most expensive books. This demonstrates how web data can be efficiently collected, cleaned, and prepared for analysis using Python.